export { SlideShell } from './SlideShell.tsx'
export { TitleSlide } from './TitleSlide.tsx'
export { SectionSlide } from './SectionSlide.tsx'
export { StatementSlide } from './StatementSlide.tsx'
export { BulletBoard, type BoardItem } from './BulletBoard.tsx'
export { TwoColumn } from './TwoColumn.tsx'
export { TimelineSlide, type TimelineStop } from './TimelineSlide.tsx'
export { DataTable } from './DataTable.tsx'
export { StatBoard, type Stat } from './StatBoard.tsx'
export { TerminalSlide, type TerminalLine } from './TerminalSlide.tsx'
export { QuoteSlide } from './QuoteSlide.tsx'
export { ImageSlide } from './ImageSlide.tsx'
export { ScreenshotPairSlide, type ScreenshotPanel } from './ScreenshotPairSlide.tsx'
export { ClosingSlide } from './ClosingSlide.tsx'
